language: node_js
version: 1.0
node_js: "12"
cache:
  directories:
    - maas-schemas/node_modules # Our node modules
    - $HOME/.npm # Globally installed packages, e.g. NPM

install:
  - yarn --cwd maas-schemas
  - yarn --cwd maas-schemas-ts

stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      script:
        - yarn --cwd maas-schemas ci
        - yarn --cwd maas-schemas-ts ci
        - node check-versions
    - stage: deploy
      script:
        - cd maas-schemas
        - yarn build
        - yarn docs
        - echo Deploying docs to GitHub pages of ${TRAVIS_REPO_SLUG}
        - git remote add origin-pages https://github:${GITHUB_API_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - yarn gh-pages -o origin-pages
      deploy:
        provider: npm
        edge: true
        email: tech@maas.global
        skip_cleanup: true
        api_key: $NPM_TOKEN
      after_deploy: ./scripts/tag.sh

